[project]
name = "q_channel_approx"
version = "0.3.0"
description = "QCA code based on work by Luke, Robert, and David"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
